# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./src/main/resources/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Bere1905
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080