-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 12:48:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jym604qy2slbxiy6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jym604qy2slbxiy6` DEFAULT CHARACTER SET utf8 ;
USE `jym604qy2slbxiy6` ;

-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`priority`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`priority` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION`varchar(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`label`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`label` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION`varchar(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`phase`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`phase` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION`varchar(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`state`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`state` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION`varchar(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`version`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`version` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`sprint`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`sprint` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DATE_FROM` DATE NOT NULL,
  `DATE_TO` DATE NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `ENABLED` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`rol`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`rol` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION`varchar(255),
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`user` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `DNI` INT(11) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `ID_ROL` INT(11) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `AVATAR` VARCHAR(255) NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `UPDATED_AT` DATETIME NOT NULL,
  `ENABLED` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USER-ROL_idx` (`ID_ROL` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`ISSUE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`issue` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `AVATAR` VARCHAR(255) NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `PRIORITY` varchar(255) NOT NULL,
  `LABEL` varchar(255) NULL,
  `PHASE` varchar(255) NULL,
  `STATE` varchar(255) NOT NULL,
  `VERSION` varchar(255) NULL,
  `ASSIGNEE` varchar(255) NULL,
  `REPORTER` varchar(255) NOT NULL,
  `ID_WATCHER` INT NULL,
  `CREATED` DATETIME NOT NULL,
  `UPDATED` DATETIME NOT NULL,
  `RESOLVED` DATETIME NULL,
  `PLANNED_START` DATETIME NULL,
  `PLANNED_END` DATETIME NULL,
  `ESTIMATED` INT NULL,
  `REMAINING` INT NULL,
  `ID_SPRINT` INT NULL,
  `BACKLOG` TINYINT NOT NULL,
  `ENABLED` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ISSUE-SPRINT_idx` (`ID_SPRINT` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`comment`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`comment` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCTIPTION` VARCHAR(255) NOT NULL,
  `ID_ISSUE` INT(11) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COMMENT-ISSUE_idx` (`ID_ISSUE` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`daily`
-- -----------------------------------------------------

CREATE TABLE IF NOT
EXISTS `jym604qy2slbxiy6`.`daily` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `AVATAR` VARCHAR(255),
  `CREATED_AT` DATE NOT NULL,
  PRIMARY KEY (`ID`));

-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`daily`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`daily_item` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `USER_NAME` VARCHAR(255) NOT NULL,
  `AVATAR` VARCHAR(255),
  `YESTERDAY` TEXT NULL DEFAULT NULL,
  `TODAY` TEXT NULL DEFAULT NULL,
  `DAILY_ID` INT(11),
  `CREATED_AT` DATE NOT NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE daily_item ADD CONSTRAINT FK_DAILY FOREIGN KEY (DAILY_ID) REFERENCES daily (ID);


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`substask`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`substask` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ISSUE` INT(11) NOT NULL,
  `ID_PHASE` INT(11) NULL DEFAULT NULL,
  `ID_STATE` INT(11) NOT NULL,
  `ID_ASSIGNEE` INT(11) NULL DEFAULT NULL,
  `ID_REPORTER` INT(11) NOT NULL,
  `UPDATED_AT` DATETIME NOT NULL,
  `RESOLVED` DATETIME NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SUBTASK-ASSIGNEE_idx` (`ID_ASSIGNEE` ASC),
  INDEX `SUBTASK-REPORTER_idx` (`ID_REPORTER` ASC),
  INDEX `SUBTASK-ISSUE_idx` (`ID_ISSUE` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jym604qy2slbxiy6`.`watcher-issue`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`watcher-issue` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_WATCHER` INT(11) NOT NULL,
  `ID_ISSUE` INT(11) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `WATCHER-USER_idx` (`ID_WATCHER` ASC),
  INDEX `WATCHER-ISSUE_idx` (`ID_ISSUE` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
