-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 12:48:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jym604qy2slbxiy6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jym604qy2slbxiy6` DEFAULT CHARACTER SET utf8 ;
USE `jym604qy2slbxiy6` ;

CREATE TABLE IF NOT EXISTS `jym604qy2slbxiy6`.`phase` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 7
  DEFAULT CHARACTER SET = utf8;


ALTER TABLE `jym604qy2slbxiy6`.`phase`
ADD COLUMN `DESCRIPTION` VARCHAR (255)