-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 12:48:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectfinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectfinal` ;

-- -----------------------------------------------------
-- Schema projectfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectfinal` DEFAULT CHARACTER SET utf8 ;
USE `projectfinal` ;

-- -----------------------------------------------------
-- Table `projectfinal`.`priority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`priority` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`priority` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`label` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`label` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`phase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`phase` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`phase` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`state` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`state` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`version` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`version` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`sprint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`sprint` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`sprint` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DATE_FROM` DATETIME NOT NULL,
  `DATE_TO` DATETIME NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `ENABLED` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`rol` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`rol` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`user` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`user` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `DNI` INT(11) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `ID_ROL` INT(11) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `UPDATED_AT` DATETIME NOT NULL,
  `ENABLED` TINYINT(4) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USER-ROL_idx` (`ID_ROL` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`ISSUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`ISSUE` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`issue` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `ID_PRIORITY` INT NOT NULL,
  `ID_LABEL` INT NULL,
  `ID_PHASE` INT NULL,
  `ID_STATE` INT NOT NULL,
  `ID_VERSION` INT NULL,
  `ID_ASSIGNEE` INT NULL,
  `ID_REPORTER` INT NOT NULL,
  `ID_WATCHER` INT NULL,
  `CREATED` DATETIME NOT NULL,
  `UPDATED` DATETIME NOT NULL,
  `RESOLVED` DATETIME NULL,
  `PLANNED_START` DATETIME NULL,
  `PLANNED_END` DATETIME NULL,
  `ESTIMATED` INT NULL,
  `REMAINING` INT NULL,
  `ID_SPRINT` INT NULL,
  `BACKLOG` TINYINT NOT NULL,
  `ENABLED` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ISSUE-PRIORITY_idx` (`ID_PRIORITY` ASC),
  INDEX `ISSUE-LABEL_idx` (`ID_LABEL` ASC),
  INDEX `ISSUE-PHASE_idx` (`ID_PHASE` ASC),
  INDEX `ISSUE-STATE_idx` (`ID_STATE` ASC),
  INDEX `ISSUE-VERSION_idx` (`ID_VERSION` ASC),
  INDEX `ISSUE-SPRINT_idx` (`ID_SPRINT` ASC),
  INDEX `ISSUE-ASSIGNEE_idx` (`ID_ASSIGNEE` ASC),
  INDEX `ISSUE-REPORTER_idx` (`ID_REPORTER` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`comment` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`comment` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCTIPTION` VARCHAR(255) NOT NULL,
  `ID_ISSUE` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COMMENT-ISSUE_idx` (`ID_ISSUE` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`daily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`daily` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`daily` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_SCRUMMASTER` INT(11) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DAILY-SCRUMMASTER_idx` (`ID_SCRUMMASTER` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `projectfinal`.`daily-user`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `projectfinal`.`daily_user`;

CREATE TABLE IF NOT EXISTS `projectfinal`.`daily_user` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DAILY_ID` INT(11) NOT NULL,
  `USER_ID` INT(11) NOT NULL,
  `YESTERDAY` VARCHAR(255),
  `TODAY` VARCHAR(255),
  PRIMARY KEY (`ID`)
);

-- -----------------------------------------------------
-- Table `projectfinal`.`member_day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`member_day` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`member_day` (
  `ID` INT(11) NOT NULL,
  `ID_USER` INT(11) NOT NULL,
  `ID_DAILY` INT(11) NOT NULL,
  `COMMENT` TEXT NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DAILY-MEMBER_DAILY_idx` (`ID_DAILY` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`substask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`substask` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`substask` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_ISSUE` INT(11) NOT NULL,
  `ID_PHASE` INT(11) NULL DEFAULT NULL,
  `ID_STATE` INT(11) NOT NULL,
  `ID_ASSIGNEE` INT(11) NULL DEFAULT NULL,
  `ID_REPORTER` INT(11) NOT NULL,
  `UPDATED_AT` DATETIME NOT NULL,
  `RESOLVED` DATETIME NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SUBTASK-ASSIGNEE_idx` (`ID_ASSIGNEE` ASC),
  INDEX `SUBTASK-REPORTER_idx` (`ID_REPORTER` ASC),
  INDEX `SUBTASK-ISSUE_idx` (`ID_ISSUE` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectfinal`.`watcher-issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectfinal`.`watcher-issue` ;

CREATE TABLE IF NOT EXISTS `projectfinal`.`watcher-issue` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_WATCHER` INT(11) NOT NULL,
  `ID_ISSUE` INT(11) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `WATCHER-USER_idx` (`ID_WATCHER` ASC),
  INDEX `WATCHER-ISSUE_idx` (`ID_ISSUE` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
